{
 "title": "Anomalous Activity for Time",
 "time": { "from": "2020-07-26T23:18:30.000Z", "to": "2020-07-27T17:20:10.000Z" },
 "templating": {
  "list": [
   { "name": "Template_id", "query": "postgres" },
   { "name": "Ver", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \nanomaly_host_detail.unit_name as \"Host\"\nFROM word_scores_by_time_window_and_template\nJOIN anomaly_host_detail ON anomaly_host_detail.id = time_window_id\nWHERE word_contribution > 0 and word_scores_by_time_window_and_template.template_id = '$Template_id' and word_scores_by_time_window_and_template.template_version = '$Ver'\nGROUP BY anomaly_host_detail.unit_name\n"
    }
   ]
  },
  {
   "title": "Anomaly Detail for set of Anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\"Anomaly Time\",\r\ntime_window_id as \"Identifier\",\r\ntemplate_id as \"Template\",\r\ntemplate_version as \"Version\",\r\nanomalous_score as \"Anomaly Score\"\r\nFROM anom_detail_list \r\nWHERE \"Anomaly Time\" BETWEEN $__from AND $__to and template_id = '$Template_id' and template_version = '$Ver';"
    }
   ]
  },
  {
   "title": "Frequently Occurring Terms",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 9, "w": 14, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "select \nword_sentiment as \"Tag/Words\", \nsum(word_contribution) as \"Count\"\nFROM word_scores_by_time_window_and_template\nINNER JOIN (SELECT anomaly_detail.id, anomaly_detail.version\nFROM anomaly_detail\nINNER JOIN (SELECT time_window_id\nFROM word_scores_by_time_window_and_template\nINNER JOIN time_windows ON time_window_id = time_windows.id\nWHERE time_windows.anomalous = TRUE and start_time BETWEEN $__from AND $__to and word_contribution > 0 and word_scores_by_time_window_and_template.template_id = '$Template_id' and word_scores_by_time_window_and_template.template_version = '$Ver') a\nON anomaly_detail.time_window_id = a.time_window_id) b\nON word_scores_by_time_window_and_template.template_id = b.id and word_scores_by_time_window_and_template.template_version = b.version\nWHERE word_contribution > 0\nGROUP BY word_sentiment;"
    }
   ]
  }
 ]
}