{
 "title": "SliceUpHomeWordCloud",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Log_Template", "query": "%" },
   {
    "name": "LogTempLoad",
    "query": "select\ntemplate_id as \"Template\",\nmax_anomalous_score as \"Criticality\"\nFrom anom_highest_contrib_template\nwhere max_start_time BETWEEN $__from AND $__to\norder by \"Criticality\" DESC;"
   },
   { "name": "Ver", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "Logs and Anomalies Over Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# of Logs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time /1000 AS \"time\",\n  sum as \"# of Logs\"\nFROM logs_over_time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  start_time/1000 AS \"time\",\n  anomalous_score as \"Critical Anomaly Score\"\nFROM anomaly_host_detail\nwhere anomalous_score > 6\ngroup by start_time, anomalous_score\nORDER BY start_time\n"
    },
    {
     "rawSql": "SELECT\n  start_time/1000 AS \"time\",\n  sum (anomalous_score) as \"Important Anomaly Score\"\nFROM anomaly_host_detail\nwhere anomalous_score > 3.7 and anomalous_score < 6\ngroup by start_time\nORDER BY start_time\n"
    },
    {
     "rawSql": "SELECT\n  start_time/1000 AS \"time\",\n  sum (anomalous_score) as \"Low Anomaly Score\"\nFROM anomaly_host_detail\nwhere anomalous_score < 3.7\ngroup by start_time\nORDER BY start_time\n"
    }
   ]
  },
  {
   "title": "Anomalies by Highest Contributing Log Template",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT max(\"Anomaly Time\") AS \"Most Recent\",\n       max(anomalous_score) AS \"Criticality\",\n       count(time_window_id) AS \"Occurrences\",\n       template_id as \"Template\",\n       template_version as \"Version\"\nFROM\n    anom_detail_list\nWHERE \"Anomaly Time\" BETWEEN $__from AND $__to\nGROUP BY template_id,\n         template_version\nORDER BY \"Criticality\" DESC;"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 11, "y": 4 },
   "targets": [
    {
     "rawSql": "select \nanomaly_host_detail.unit_name as \"Host\"\nFROM word_scores_by_time_window_and_template\nJOIN anomaly_host_detail ON anomaly_host_detail.id = time_window_id\nWHERE word_contribution > 0 and word_scores_by_time_window_and_template.template_id = '$LogTempLoad' and word_scores_by_time_window_and_template.template_version = '$Ver'\nGROUP BY anomaly_host_detail.unit_name;"
    }
   ]
  },
  {
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT word_sentiment AS \"Tag/Words\",\r\n       sum(word_contribution) AS \"Count\"\r\nFROM word_scores_by_time_window_and_template\r\nJOIN time_windows ON word_scores_by_time_window_and_template.time_window_id = time_windows.id\r\nWHERE word_contribution > 0\r\n    AND time_windows.start_time BETWEEN $__from AND $__to\r\n    AND word_scores_by_time_window_and_template.template_id LIKE '$Log_Template%'\r\nGROUP BY word_sentiment;"
    }
   ]
  },
  {
   "title": "Template",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  template\nFROM templates\nwhere id = '$LogTempLoad' and version = '$Ver';"
    }
   ]
  }
 ]
}