{
 "title": "Template Details",
 "time": { "from": "2020-06-24T21:51:30.000Z", "to": "2020-06-24T22:18:20.000Z" },
 "templating": {
  "list": [
   { "name": "table_name", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Template: $table_name",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select template\nfrom templates \nwhere table_name = '$table_name';"
    }
   ]
  },
  {
   "title": "Template Records for $table_name",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT * FROM $table_name limit 100\n"
    }
   ]
  },
  {
   "title": "Random Raw Log Examples $table_name",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\nrecord\nFROM\n  log_examples\nWHERE\n table_name = '$table_name'\n"
    }
   ]
  }
 ]
}