{
 "title": "TemplateHome",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Logs Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time /1000 AS \"time\",\n  sum\nFROM logs_over_time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Anomalies Over Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  count (unit_name)\n  FROM max_anomaly_host\n  group by start_time"
    }
   ]
  },
  {
   "title": "Max Anomaly by Host",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now () AS \"time\",\n  unit_name AS metric,\n  max (anomalous_score)\nFROM max_anomaly_host\nWHERE start_time BETWEEN $__from AND $__to\ngroup by unit_name\norder by max desc limit 100"
    }
   ]
  },
  {
   "title": "Template Count",
   "type": "bargauge",
   "gridPos": { "h": 25, "w": 9, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now () AS \"time\",\n  table_name AS metric,\n  sum (sum)\nFROM template_count\nWHERE start_time BETWEEN $__from AND $__to\ngroup by table_name\norder by sum desc limit 100\n\n"
    }
   ]
  },
  {
   "title": "Logs By Host",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now () AS \"time\",\n  unit_name AS metric,\n  sum (total_count)\nFROM logs_by_host\nWHERE start_time BETWEEN $__from AND $__to\nGROUP BY unit_name\nORDER BY sum desc"
    }
   ]
  }
 ]
}